
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/financial?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
  jpa:
    database: mysql
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    username:
    password:
    protocol: smtp
    default-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.cwgl.entity

logging:
  level:
    root: info
    org:
      springframework:
        web: info
    com.example.cwgl.dao: debug

